#!/usr/bin/env bash

#Full location of config yaml file
configFilePath="/home/aravind/aem_automation_scripts/config.yaml"

function parse_yaml {
   local prefix=$2
   local s='[[:space:]]*' w='[a-zA-Z0-9_]*' fs=$(echo @|tr @ '\034')
   sed -ne "s|^\($s\):|\1|" \
        -e "s|^\($s\)\($w\)$s:$s[\"']\(.*\)[\"']$s\$|\1$fs\2$fs\3|p" \
        -e "s|^\($s\)\($w\)$s:$s\(.*\)$s\$|\1$fs\2$fs\3|p"  $1 |
   awk -F$fs '{
      indent = length($1)/2;
      vname[indent] = $2;
      for (i in vname) {if (i > indent) {delete vname[i]}}
      if (length($3) > 0) {
         vn=""; for (i=0; i<indent; i++) {vn=(vn)(vname[i])("_")}
         printf("%s%s%s=\"%s\"*", "'$prefix'",vn, $2, $3);
      }
   }'
}

eval $(parse_yaml $configFilePath)

mailPath=$mailPath
aemPath=$aemPath
autofix=$autofix
stoptime=$aemstoptime
starttime=$aemstarttime
email=$email
secretpass=$emailsecretkey
aemuser=$aemusername
aemgroup=$aemgroupname

if [ "$(id -u)" -ne 0 ]
then
    echo "[!] Please run as super user"
    exit 1
fi

mails=()
readarray -t mails < $mailPath

isAuthor=false
isPublish=false


if [ -d "${aemPath}/author" ]
then
    isAuthor=true
fi

if [ -d "${aemPath}/publish" ]
then
    isPublish=true
fi

toCheck=0

sendmail (){
  sender=$email
  pass=$secretpass
  rcpt=""
  to=""
  hostname=`hostname`
  subject="AEM Owner Change Alert"
  contentType="Content-Type: text/html; charset=utf-8"
  body=""
  if $3
  then
    body="<p>AEM Instance(s) <strong>$1 $2</strong> in <strong>$hostname</strong> ownership changed. <strong>Fix deployed. Autofix is enabled</strong></p>*"
  else
    body="<p>AEM Instance(s) <strong>$1 $2</strong> in <strong>$hostname</strong> ownership changed. <strong>Please take required action. Autofix is disabled</strong></p>*"
  fi
  for mail in "${mails[@]}"
  do
      mailrcpt="--mail-rcpt "
      rcpt+="$mailrcpt $mail "
      to+="$mail,"
  done
  
  mailcmd=`curl -s --url 'smtps://smtp.gmail.com:465' --ssl-reqd --mail-from $sender  $rcpt --user $sender:$pass -T <(echo -e "From: $sender*To: $to*Subject: $subject*$contentType*$body")`
  echo "[+] e-mail sent"
}

checkOwner () {
    Fix=0
    local array=()
    local i=0
    for path in `find $1 -not -group $aemgroup -or -not -user $aemuser`
    do
        array[$i]="$path"
        i=$i+1
    done
    len=${#array[*]}
    if [ $len -ne 0 ]
    then
        echo "Owner changed Files Count for location ($1) : $len"
        echo "--------------------------------------------------------------------------------------------------------------------" 
        if $autofix
        then
            if chown -R aem:aem "$1/crx-quickstart"
            then
                echo "[+] Fix Applied for location ($1)"
                
                if su - aem -c "$1/crx-quickstart/bin/stop" 
                then
                    echo "stopping ($1)..."
                    sleep $stoptime
                fi
                if su - aem -c "$1/crx-quickstart/bin/start"
                then
                    echo "starting ($1)..."
                    sleep $starttime 
                fi
                echo "[+] aem ($1) server restarted"
               

            else
                echo "[-] Fix Failed for location ($1)"
            fi
        else
            echo "[!] Autofix disabled"
        fi
        Fix=1
    else
        echo "[+] No owner change files found for location ($1)!"
        Fix=0
    fi
    return $Fix
}



if $isAuthor -a $isPublish
then
    echo "Both Author and Publish Found"
    toCheck=2
elif  $isAuthor
then
    echo "Author found"
    toCheck=0
elif $isPublish 
then
    toCheck=1
    echo "Publish found"
else
    echo "[!] No Author or Publish Found. Try again with the correct path"
fi

if [ $toCheck -ne 2 ]
then
    if [ $toCheck -eq 0 ]
    then
        checkOwner "${aemPath}/author"
        res=$?
        if [ res -eq 0 ]
        then
            sendmail "${aemPath}/author" "" $autofix
        else
            echo "No mail sent. No Owner change"
        fi
    elif [ $toCheck -eq 1 ]
    then
        checkOwner "${aemPath}/publish"
        res=$?
        if [ res -eq 0 ]
        then
            sendmail "" "${aemPath}/publish" $autofix
        else
            echo "No mail sent. No Owner change"
        fi
    else
        echo "[!] Incorrect Choice"
        exit 1
    fi
else
    FixAuthor=1
    FixPublish=1
    checkOwner "${aemPath}/author"
    FixAuthor=$?
    checkOwner "${aemPath}/publish"
    FixPublish=$?

    if [ $FixAuthor -eq 0 -a $FixPublish -eq 0 ]
    then
        echo "No mail sent. No Owner change"
    elif [ $FixAuthor -eq 1 -a $FixPublish -eq 1 ]
    then
        sendmail "${aemPath}/author" "${aemPath}/publish" $autofix
    elif [ $FixAuthor -eq 1 ]
    then
        sendmail "${aemPath}/author" "" $autofix
    elif [ $FixPublish -eq 1 ]
    then
        sendmail "" "${aemPath}/publish" $autofix
    else
        echo ""
    fi
fi
