inboundcertsfolder: cert-uploads/inbound
outboundcertsfolder: cert-uploads/outbound

certtypes:
  inbound:
    - axol
    - polaris
    - redeem
    - rewards
    - privatekey
  outbound:
    connexions:
      - getConnexionsPrivateKeyString
      - getConnexionsEncryptionCert
      - getConnexionsX509CertString
    ro:
      - getRoPrivateKeyString
      - getRoEncryptionCert
      - getRoX509CertString
    promo:
      - getPromoPrivateKeyString
      - getPromoEncryptionCert
      - getPromoX509CertString

environments:
  prod:
    - host: "localhost"
      port: "4503"
      username: "admin"
      password: "admin"
      inboundosgipaths:
        axol: <osgipath>
        polaris:  <osgipath>
        redeem: <osgipath>
        rewards:  <osgipath>
        privatekey:  <osgipath>
      outboundosgipath: <osgipath>



    - host: "localhost"
      port: "4502"
      username: "admin"
      password: "admin"
      inboundosgipaths:
        axol: <osgipath>
        polaris: <osgipath>
        redeem: <osgipath>
        rewards:  <osgipath>
        privatekey:  <osgipath>
      outboundosgipath: <osgipath>

  try:    
