#please make sure all 9 configs are here

#1. give the location of the installation of aem directory
aemPath: /opt/aem

#2. give the full location of the txt file containing mails that require notification
mailPath: /home/aravind/aem_automation_scripts/mails.txt

#3. configuration mail id that is used to send email
email: dummy@dummy.com

#4. configuration mail secret key that is used to send email  
emailsecretkey: dummy #dummy passwd

#5. Enter the linux username with which your aem app should be running as
aemusername: aem

#6. Enter the linux groupname with which your aem app should be running as
aemgroupname: aem

#7. If you want the script to fix the ownership issue automatically and then inform you set value to true else false
autofix: false

#8. If autofix is enabled then the time required to wait after stopping aem
aemstoptime: 30

#9. If autofix is enabled then the time required to wait after starting aem
aemstarttime: 60
